title: Jensen Hsiao's Blog
email: jensenxiao@gmail.com
author: Jensen Hsiao

copyright: "Unpublished Work (cleft) 2023-{currentYear}.  {author}"

description: >-
  Documents my learning experiences.

baseurl: ""
url: "https://jensenxiao.github.io"
favicon: ""

yat:
  date_format: "%b %d, %Y"

# debug: false

# header_transparent: true

sitemap: true

night_mode: "off"

header_pages:
  - index.html
  - archives.html
  - categories.html
  - tags.html
  - about.md

paginate: 5

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
